services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - back-volume:/app/src
    environment:
      - PORT=3000
      - AES_SECRET_KEY=0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef

volumes:
  back-volume:
    driver: local
